CREATE TABLE places (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	address text NULL,
	app bool NULL,
	date_created timestamp NULL,
	last_updated timestamp NULL,
	"name" varchar(255) NULL,
	order_ahead bool NULL,
	website varchar(255) NULL,
	created_by varchar(255) NULL,
	modified_by varchar(255) NULL,
	CONSTRAINT places_pkey PRIMARY KEY (id),
	CONSTRAINT uk_place_name UNIQUE (name)
);
