CREATE TABLE deals (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	date_created timestamp NULL,
	description text NOT NULL,
	last_updated timestamp NULL,
	place_id int8 NULL,
	dish text NULL,
	created_by varchar(255) NULL,
	modified_by varchar(255) NULL,
	max_discount float8 NULL,
	max_discount_percent float8 NULL,
	max_price float8 NULL,
	min_discount float8 NULL,
	min_discount_percent float8 NULL,
	min_price float8 NULL,
	tax_included bool NULL,
	verified bool NULL,
	end_time varchar(255) NULL,
	start_time varchar(255) NULL,
	end_date date NULL,
	start_date date NULL,
	CONSTRAINT deals_pkey PRIMARY KEY (id)
);

ALTER TABLE public.deals ADD CONSTRAINT fk_deals_places FOREIGN KEY (place_id) REFERENCES places(id);
