CREATE TABLE days (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"date" date NULL,
	date_created timestamp NULL,
	day_of_week int4 NULL,
	last_updated timestamp NULL,
	deal_id int8 NULL,
	created_by varchar(255) NULL,
	modified_by varchar(255) NULL,
	CONSTRAINT days_pkey PRIMARY KEY (id)
);

ALTER TABLE public.days ADD CONSTRAINT fk_days_deals FOREIGN KEY (deal_id) REFERENCES deals(id);
