CREATE TABLE public.users (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	username varchar(100) NOT NULL,
	"password" varchar(500) NOT NULL,
	enabled bool NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (username)
)
TABLESPACE pg_default;

ALTER TABLE users
    OWNER to postgres;

---

CREATE TABLE public.authorities (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username varchar(100) NOT NULL,
  authority varchar(50) NOT NULL,
  CONSTRAINT authorities_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

ALTER TABLE public.authorities ADD CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES users(username);

ALTER TABLE authorities
    OWNER to postgres;

---

CREATE TABLE public.places (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	date_created timestamptz(6) NULL,
	last_updated timestamptz(6) NULL,
	created_by varchar(100) NULL,
	modified_by varchar(255) NULL,
	address text NULL,
	app bool NULL,
	"name" varchar(255) NULL,
	order_ahead bool NULL,
	website varchar(255) NULL,
	CONSTRAINT places_pkey PRIMARY KEY (id),
	CONSTRAINT uk_places_name UNIQUE ("name")
)
TABLESPACE pg_default;

ALTER TABLE users
    OWNER to postgres;

---

CREATE TABLE public.deals (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	place_id int8 NULL,
	date_created timestamptz(6) NULL,
	last_updated timestamptz(6) NULL,
	created_by varchar(100) NULL,
	modified_by varchar(100) NULL,
	deal_type int2 NULL,
	description text NOT NULL,
	dish text NULL,
	end_date date NULL,
	end_time varchar(255) NULL,
	max_discount float8 NULL,
	max_discount_percent float8 NULL,
	max_price float8 NULL,
	min_discount float8 NULL,
	min_discount_percent float8 NULL,
	min_price float8 NULL,
	start_date date NULL,
	start_time varchar(255) NULL,
	tax_included bool NULL,
	verified bool NULL,
	CONSTRAINT deals_deal_type_check CHECK (((deal_type >= 0) AND (deal_type <= 4))),
	CONSTRAINT deals_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

ALTER TABLE public.deals ADD CONSTRAINT fk_deals_places FOREIGN KEY (place_id) REFERENCES public.places(id);

ALTER TABLE deals
    OWNER to postgres;

---

CREATE TABLE public.days (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	deal_id int8 NULL,
	date_created timestamptz(6) NULL,
	last_updated timestamptz(6) NULL,
	created_by varchar(100) NULL,
	modified_by varchar(100) NULL,
	"date" date NULL,
	day_of_week int2 NULL,
	CONSTRAINT days_day_of_week_check CHECK (((day_of_week >= 0) AND (day_of_week <= 6))),
	CONSTRAINT days_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

ALTER TABLE public.days ADD CONSTRAINT fk_days_deals FOREIGN KEY (deal_id) REFERENCES public.deals(id);

ALTER TABLE public.days
    OWNER to postgres;

---

CREATE TABLE public.deal_logs (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	deal_id int8 NULL,
	place_id int8 NULL,
	deal_type int2 NULL,
	description text NOT NULL,
	redeemed bool NULL,
	redemption_date date NULL,
	date_created timestamptz(6) NULL,
	last_updated timestamptz(6) NULL,
	created_by varchar(100) NULL,
	modified_by varchar(100) NULL,
	CONSTRAINT deal_log_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

ALTER TABLE public.deal_logs ADD CONSTRAINT fk_deal_logs_deals FOREIGN KEY (deal_id) REFERENCES public.deals(id);
ALTER TABLE public.deal_logs ADD CONSTRAINT fk_deal_logs_places FOREIGN KEY (place_id) REFERENCES public.places(id);

ALTER TABLE public.deal_logs
    OWNER to postgres;

---

CREATE TABLE public.rewards (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	place_id int8 NOT NULL,
	notes text NULL,
	reward_type int2 NULL,
	date_created timestamptz(6) NULL,
	last_updated timestamptz(6) NULL,
	created_by varchar(100) NULL,
	modified_by varchar(100) NULL,
	CONSTRAINT rewards_pkey PRIMARY KEY (id),
	CONSTRAINT rewards_reward_type_check CHECK (((reward_type >= 0) AND (reward_type <= 3)))
)
TABLESPACE pg_default;

ALTER TABLE public.rewards ADD CONSTRAINT fk_rewards_places FOREIGN KEY (place_id) REFERENCES public.places(id);

ALTER TABLE public.rewards
    OWNER to postgres;

---

CREATE TABLE public.uploads (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	deal_id int8 NOT NULL,
	verified bool NULL,
	image bytea NULL,
	date_created timestamptz(6) NULL,
	last_updated timestamptz(6) NULL,
	created_by varchar(100) NULL,
	modified_by varchar(100) NULL,
	CONSTRAINT uploads_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

ALTER TABLE public.uploads ADD CONSTRAINT fk_uploads_deals FOREIGN KEY (deal_id) REFERENCES public.deals(id);

ALTER TABLE public.uploads
		OWNER to postgres;

---
