logging:
  file:
    name: ./logs/mpls-food.log
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

spring:
  config:
    activate:
      on-profile: dev
  graphql:
    graphiql:
      enabled: true
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 25MB
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/mpls-food}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    dbcp2:
      validation-query: SELECT 1
  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  sql:
    init:
      platform: postgresql
      schema-locations: classpath:db/schema.sql
      data-locations: optional:classpath*:db/data.sql
      mode: never # set to 'always' to create and populate the database on startup

management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  pathsToMatch: /api/**
