spring:
  config:
    activate:
      on-profile: h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:mpls-food
    username: sa
    driverClassName: org.h2.Driver

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/mpls-food}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:<<YOUR_PASSWORD>>}
    driver-class-name: org.postgresql.Driver

    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

