CREATE TABLE public.users (
	id bigserial NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	username varchar(100) NOT NULL,
	"password" varchar(500) NOT NULL,
	enabled bool NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (username)
)
TABLESPACE pg_default;

ALTER TABLE users
    OWNER to postgres;
