CREATE TABLE public.authorities (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username varchar(100) NOT NULL,
  authority varchar(50) NOT NULL,
  CONSTRAINT authorities_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

ALTER TABLE public.authorities ADD CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES users(username);


ALTER TABLE authorities
    OWNER to postgres;
