CREATE TABLE public.places (
	id bigserial NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	date_created timestamptz(6) NULL,
	last_updated timestamptz(6) NULL,
	created_by varchar(100) NULL,
	modified_by varchar(255) NULL,
	address text NULL,
	app bool NULL,
	"name" varchar(255) NULL,
	order_ahead bool NULL,
	website varchar(255) NULL,
	CONSTRAINT places_pkey PRIMARY KEY (id),
	CONSTRAINT uk_places_name null
);

TABLESPACE pg_default;

ALTER TABLE users
    OWNER to postgres;
