CREATE TABLE IF NOT EXISTS public.places
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    address text NULL,
    app bool NULL,
    date_created timestamp NULL,
    last_updated timestamp NULL,
    "name" varchar(255) NULL,
    order_ahead bool NULL,
    website varchar(255) NULL,
    CONSTRAINT places_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.places
    OWNER to postgres;
