CREATE TABLE public.deals (
	id bigserial NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	place_id int8 NULL,
	date_created timestamptz(6) NULL,
	last_updated timestamptz(6) NULL,
	created_by varchar(100) NULL,
	modified_by varchar(100) NULL,
	deal_type int2 NULL,
	description text NOT NULL,
	dish text NULL,
	end_date date NULL,
	end_time varchar(255) NULL,
	max_discount float8 NULL,
	max_discount_percent float8 NULL,
	max_price float8 NULL,
	min_discount float8 NULL,
	min_discount_percent float8 NULL,
	min_price float8 NULL,
	start_date date NULL,
	start_time varchar(255) NULL,
	tax_included bool NULL,
	verified bool NULL,
	CONSTRAINT deals_deal_type_check CHECK (((deal_type >= 0) AND (deal_type <= 4))),
	CONSTRAINT deals_pkey PRIMARY KEY (id)
);

TABLESPACE pg_default;

ALTER TABLE public.deals ADD CONSTRAINT fk_deals_places FOREIGN KEY (place_id) REFERENCES public.places(id);

ALTER TABLE deals
    OWNER to postgres;
