CREATE TABLE days (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "date" date NULL,
  date_created timestamp NOT NULL,
  day_of_week int NULL,
  last_updated timestamp NOT NULL,
  deal_id bigint NULL,
  CONSTRAINT days_pkey PRIMARY KEY (id)
);

ALTER TABLE days ADD CONSTRAINT fk_days_deals FOREIGN KEY (deal_id) REFERENCES deal(id);

TABLESPACE pg_default;

ALTER TABLE public.deals
    OWNER to postgres;
