CREATE TABLE public.days (
	id bigserial NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	deal_id int8 NULL,
	date_created timestamptz(6) NULL,
	last_updated timestamptz(6) NULL,
	created_by varchar(100) NULL,
	modified_by varchar(100) NULL,
	"date" date NULL,
	day_of_week int2 NULL,
	CONSTRAINT days_day_of_week_check CHECK (((day_of_week >= 0) AND (day_of_week <= 6))),
	CONSTRAINT days_pkey PRIMARY KEY (id)
);

TABLESPACE pg_default;

ALTER TABLE public.days ADD CONSTRAINT fk_days_deals FOREIGN KEY (deal_id) REFERENCES public.deals(id);

ALTER TABLE public.days
    OWNER to postgres;
