CREATE TABLE public.deal_logs (
	id bigserial NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	deal_id int8 NULL,
	place_id int8 NULL,
	deal_type int2 NULL,
	description text NOT NULL,
	redeemed bool NULL,
	redemption_date date NULL,
	date_created timestamptz(6) NULL,
	last_updated timestamptz(6) NULL,
	created_by varchar(100) NULL,
	modified_by varchar(100) NULL,
	CONSTRAINT deal_log_pkey PRIMARY KEY (id)
);

TABLESPACE pg_default;

ALTER TABLE public.deal_logs ADD CONSTRAINT fk_deal_logs_deals FOREIGN KEY (deal_id) REFERENCES public.deals(id);
ALTER TABLE public.deal_logs ADD CONSTRAINT fk_deal_logs_places FOREIGN KEY (place_id) REFERENCES public.places(id);

ALTER TABLE public.deal_logs
    OWNER to postgres;
