CREATE TABLE deal_day (
  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "date" date NULL,
  date_created timestamp NOT NULL,
  day_of_week int4 NULL,
  last_updated timestamp NOT NULL,
  deal_id int8 NULL,
  CONSTRAINT deal_day_pkey PRIMARY KEY (id)
);


ALTER TABLE  deal_day ADD CONSTRAINT fkieu000uv20soeiy77xh7juvwh FOREIGN KEY (deal_id) REFERENCES deal(id);