CREATE TABLE public.rewards (
	id bigserial NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	place_id int8 NOT NULL,
	notes text NULL,
	reward_type int2 NULL,
	date_created timestamptz(6) NULL,
	last_updated timestamptz(6) NULL,
	created_by varchar(100) NULL,
	modified_by varchar(100) NULL,
	CONSTRAINT rewards_pkey PRIMARY KEY (id),
	CONSTRAINT rewards_reward_type_check CHECK (((reward_type >= 0) AND (reward_type <= 3)))
);

TABLESPACE pg_default;

ALTER TABLE public.rewards ADD CONSTRAINT fk_rewards_places FOREIGN KEY (place_id) REFERENCES public.places(id);

ALTER TABLE public.rewards
    OWNER to postgres;
