CREATE TABLE public.uploads (
	id bigserial NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	deal_id int8 NOT NULL,
	verified bool NULL,
	image bytea NULL,
	date_created timestamptz(6) NULL,
	last_updated timestamptz(6) NULL,
	created_by varchar(100) NULL,
	modified_by varchar(100) NULL,
	CONSTRAINT uploads_pkey PRIMARY KEY (id)
);

TABLESPACE pg_default;

ALTER TABLE public.uploads ADD CONSTRAINT fk_uploads_deals FOREIGN KEY (deal_id) REFERENCES public.deals(id);

ALTER TABLE public.uploads
		OWNER to postgres;
